{% set version = "1.18.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: gstreamer_and_plugins
  version: {{ version }}

source:
  - url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
    sha256: 0ff09245b06c0aeb5d9a156edcab088a7e8213a0bf9c84a1ff0318f9c00c7805
    patches:
      # remove when next version is released
      - 40c994cddee41954053f80dde40f56107ddfcfd4.patch 
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-{{ version }}.tar.xz
    sha256: 762abdd1a950809a1cea62fff7f86b5f7d6bd5f6841e3e585c700b823cdb7897
    folder: plugins_base
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-{{ version }}.tar.xz
    sha256: 6329bc377a3afea5cf1ab329a91cc4a906f075781780d1edc59e8bea8c1a8bac
    folder: plugins_good

build:
  number: 0

outputs:
  - name: gstreamer
    script: install_gstreamer.sh  # [unix]
    script: install_gstreamer.bat  # [win]
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gstreamer', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - {{ posix }}bison
        - {{ posix }}flex
        - meson
        - ninja
        - gobject-introspection
      host:
        - gettext
        - glib
    test:
      commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
        - test -f $PREFIX/lib/girepository-1.0/Gst-1.0.typelib  # [unix]
        - if not exist %LIBRARY_LIB%\\girepository-1.0\\Gst-1.0.typelib exit 1  # [win]
    about:
      summary: "Library for constructing graphs of media-handling components"
      description:
      doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/docs

  - name: gst-plugins-base
    script: install_base_plugins.sh  # [unix]
    script: install_base_plugins.bat  # [win]
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-base', max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # These dependencies are only for cos7 platforms
        - {{ cdt('libglvnd-glx') }}          # [linux & (ppc64le | aarch64)]
        - {{ cdt('libglvnd') }}              # [linux & (ppc64le | aarch64)]
        - {{ cdt('libxshmfence-devel') }}    # [linux & (ppc64le | aarch64)]
        - {{ cdt('mesa-khr-devel') }}        # [linux & (ppc64le | aarch64)]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - meson
        - ninja
        - gobject-introspection
      host:
        - {{ pin_subpackage('gstreamer') }}
        - glib
        - zlib
        - gettext
        - libxcb                             # [linux]
        - libpng                             # [unix]
      run:
        - {{ pin_compatible('gstreamer') }}
        - libpng                             # [unix]

    test:
      commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/girepository-1.0/GstVideo-1.0.typelib  # [unix]
        - if not exist %LIBRARY_BIN%\\gstallocators-1.0-0.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\girepository-1.0\\GstVideo-1.0.typelib exit 1  # [win]
        - gst-inspect-1.0 --plugin volume

    about:
        summary: "GStreamer Base Plug-ins"
        description: |
          GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
          GStreamer plug-ins and elements, spanning the range of possible types of
          elements one would want to write for GStreamer.
        doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs

  - name: gst-plugins-good
    script: install_good_plugins.sh  # [unix]
    script: install_good_plugins.bat  # [win]
    build:
      activate_in_script: True
      run_exports:
        - {{ pin_subpackage('gst-plugins-good', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # These dependencies are only for cos7 platforms
        - {{ cdt('libglvnd-glx') }}          # [linux & (ppc64le | aarch64)]
        - {{ cdt('libglvnd') }}              # [linux & (ppc64le | aarch64)]
        - {{ cdt('libxshmfence-devel') }}    # [linux & (ppc64le | aarch64)]
        - {{ cdt('mesa-khr-devel') }}        # [linux & (ppc64le | aarch64)]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - meson
        - ninja
      host:
        - {{ pin_subpackage('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
        - glib
        - libxcb                             # [linux]
      run:
        - {{ pin_compatible('gstreamer') }}
        - {{ pin_subpackage('gst-plugins-base') }}
    test:
      commands:
        - test -f $PREFIX/lib/gstreamer-1.0/libgstalpha${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/gstreamer-1.0/libgstdebug${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/gstreamer-1.0/libgstspectrum${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstalpha.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdebug.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstspectrum.dll exit 1  # [win]
        - gst-inspect-1.0 --plugin alpha
    about:
      summary: "GStreamer Good Plug-ins"
      description: |
        GStreamer Good Plug-ins is A collection of plug-ins you'd
        want to have right next to you on the battlefield.
        Shooting sharp and making no mistakes, these plug-ins have it
        all: good looks, good code, and good licensing.  Documented and
        dressed up in tests.  If you're looking for a role model to
        base your own plug-in on here it is.
      doc_source_url: https://github.com/GStreamer/gst-plugins-good/tree/master/docs

about:
  home: http://gstreamer.freedesktop.org/
  summary: "Library for constructing graphs of media-handling components"
  license: LGPL-2.0-or-later
  license_file: COPYING
  doc_url: https://gstreamer.freedesktop.org/documentation/
  dev_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - msarahan
    - tschoonj
