{% set version = "1.24.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: gstreamer_and_plugins
  version: {{ version }}

source:
  - url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
    sha256: 093a379602a250d5cd33b88e723757c80198317efde33893edf3c87b6e53b907
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-{{ version }}.tar.xz
    sha256: 98572c1f8b710e52673e250cd96e4f2660d79bd66aa172c5dde5f690c1231e1d
    folder: plugins_base
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-{{ version }}.tar.xz
    sha256: 94bf3b5118dd4213af66048faac830569cc9a94a8c8e59e8a6d33b315f518462
    folder: plugins_good

build:
  number: 0
  # Installing and using plugins in the conda environment isn't working for s390x, due to build options not correctly
  # translating into the location of a helper library at runtime, for this platform.
  # Audio/video tools aren't needed on s390x anyway.
  skip: True # [linux and s390x]

outputs:
  - name: gstreamer
    script: install_gstreamer.sh  # [unix]
    script: install_gstreamer.bat  # [win]
    build:
      ignore_run_exports:        # [unix]
        - gettext                # [unix]
      activate_in_script: true
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gstreamer', max_pin='x.x') }}
      missing_dso_whitelist:  # [linux]
        - $RPATH/libc.so.6  # [linux]
        - $RPATH/libm.so.6  # [linux]
        - $RPATH/libpthread.so.0  # [linux]
    requirements:
      build:
        # setuptools >= 65.0.0 is lacking the msvccompiler module in distutils.
        # https://github.com/pypa/setuptools/pull/3505
        - setuptools <65
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config
        - {{ posix }}bison
        - {{ posix }}flex
        - meson
        - ninja
        - gobject-introspection
      host:
        - gettext 0.21.0                    # [not win]
        - glib {{ glib }}
      run:
        - {{ pin_compatible('gettext') }}   # [not win]
    test:
      commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
        - test -f $PREFIX/lib/girepository-1.0/Gst-1.0.typelib  # [unix]
        - if not exist %LIBRARY_LIB%\\girepository-1.0\\Gst-1.0.typelib exit 1  # [win]
    about:
      summary: Library for constructing graphs of media-handling components
      description:
      doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/subprojects/gstreamer/docs

  - name: gst-plugins-base
    script: install_base_plugins.sh  # [unix]
    script: install_base_plugins.bat  # [win]
    build:
      ignore_run_exports:
        - gettext                    # [not win]
        - libpng                     # [linux and ppc64le]
        - libxcb                     # [linux and ppc64le]
        - libvorbis
        - libopus                    # [unix]
      activate_in_script: true
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-base', max_pin='x.x') }}
      missing_dso_whitelist:  # [linux]
        - $RPATH/libc.so.6  # [linux]
        - $RPATH/libm.so.6  # [linux]
        - $RPATH/libpthread.so.0  # [linux]
    requirements:
      build:
        # setuptools >= 65.0.0 is lacking the msvccompiler module in distutils.
        # https://github.com/pypa/setuptools/pull/3505
        - setuptools <65
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # These dependencies are only for cos7 platforms
        - {{ cdt('libglvnd-glx') }}          # [linux and (ppc64le | aarch64)]
        - {{ cdt('libglvnd') }}              # [linux and (ppc64le | aarch64)]
        - {{ cdt('libxshmfence-devel') }}    # [linux and ppc64le]
        - {{ cdt('mesa-khr-devel') }}        # [linux and (ppc64le | aarch64)]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - meson
        - ninja
        - gobject-introspection
      host:
        - {{ pin_subpackage('gstreamer', exact=True) }}
        - glib {{ glib }}
        - zlib
        - gettext 0.21.0                     # [not win]
        - libxcb  1.14.0                     # [linux]
        - libpng  1.6.37                     # [unix]
        #- alsa-lib                           # [linux]
        - libopus 1.3                        # [unix]
        - libvorbis 1.3.7
      run:
        - {{ pin_subpackage('gstreamer', exact=True) }}
        - {{ pin_compatible('libpng', max_pin='x.x') }} # [unix]
        - {{ pin_compatible('libogg') }}
        - {{ pin_compatible('gettext') }}               # [unix]
        - {{ pin_compatible('zlib', max_pin='x.x.x') }}
        - {{ pin_compatible('libvorbis') }}
        - {{ pin_compatible('libopus') }}               # [unix]
    test:
      commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/girepository-1.0/GstVideo-1.0.typelib  # [unix]
        - if not exist %LIBRARY_BIN%\\gstallocators-1.0-0.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\girepository-1.0\\GstVideo-1.0.typelib exit 1  # [win]
        - gst-inspect-1.0 --plugin volume

    about:
      summary: GStreamer Base Plug-ins
      description: |
        GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
        GStreamer plug-ins and elements, spanning the range of possible types of
        elements one would want to write for GStreamer.
      doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/subprojects/gst-plugins-base/docs

  - name: gst-plugins-good
    script: install_good_plugins.sh  # [unix]
    script: install_good_plugins.bat  # [win]
    build:
      ignore_run_exports:
        - libxcb                             # [linux]
      activate_in_script: true
      run_exports:
        - {{ pin_subpackage('gst-plugins-good', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libc.so.6  # [linux]
        - $RPATH/libm.so.6  # [linux]
        - $RPATH/libpthread.so.0  # [linux]
        - $RPATH/libdl.so.2 #[linux]
        - $RPATH/libcrypto.so.1.1 # [linux]
        - $RPATH/libcrypto.1.1.dylib # [osx]
    requirements:
      build:
        # setuptools >= 65.0.0 is lacking the msvccompiler module in distutils.
        # https://github.com/pypa/setuptools/pull/3505
        - setuptools <65
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - {{ cdt('mesa-dri-drivers') }}      # [linux]
        # These dependencies are only for cos7 platforms
        - {{ cdt('libglvnd-glx') }}          # [linux and (ppc64le | aarch64)]
        - {{ cdt('libglvnd') }}              # [linux and (ppc64le | aarch64)]
        - {{ cdt('libxshmfence-devel') }}    # [linux and ppc64le]
        - {{ cdt('mesa-khr-devel') }}        # [linux and (ppc64le | aarch64)]
        # expat here is _only_ required for mesa-dri-drivers
        - {{ cdt('expat') }}                 # [linux]
        - {{ cdt('libselinux-devel') }}      # [linux]
        - pkg-config
        - meson
        - ninja
      host:
        - {{ pin_subpackage('gstreamer', exact=True) }}
        - {{ pin_subpackage('gst-plugins-base', exact=True) }}
        - glib {{ glib }}
        - libxcb 1.14.0                      # [linux]
        - lame 3.100                         # [linux]
        - mpg123 1.30.0                      # [(linux and x86_64) or osx]
        - libpng  1.6.37                     # [unix]
        - openssl {{ openssl }}
        - bzip2 {{ bzip2 }}
      run:
        - {{ pin_subpackage('gstreamer', exact=True) }}
        - {{ pin_subpackage('gst-plugins-base', exact=True) }}
        - {{ pin_compatible('gettext') }}    # [osx]
        - {{ pin_compatible('zlib', max_pin='x.x.x') }}
        - {{ pin_compatible('libpng', max_pin='x.x') }} # [unix]
        - {{ pin_compatible('mpg123', max_pin='x.x') }} # [unix]
        - libxml2 >=2.8
    test:
      commands:
        - test -f $PREFIX/lib/gstreamer-1.0/libgstalpha${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/gstreamer-1.0/libgstdebug${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/gstreamer-1.0/libgstspectrum${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstalpha.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdebug.dll exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstspectrum.dll exit 1  # [win]
        - gst-inspect-1.0 --plugin alpha
    about:
      summary: GStreamer Good Plug-ins
      description: |
        GStreamer Good Plug-ins is A collection of plug-ins you'd
        want to have right next to you on the battlefield.
        Shooting sharp and making no mistakes, these plug-ins have it
        all: good looks, good code, and good licensing.  Documented and
        dressed up in tests.  If you're looking for a role model to
        base your own plug-in on here it is.
      doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/subprojects/gst-plugins-good/docs

about:
  home: https://gstreamer.freedesktop.org/
  summary: Library for constructing graphs of media-handling components
  license: LGPL-2.0-or-later
  license_file: COPYING
  license_family: LGPL
  description: |
    The applications it supports range from simple Ogg/Vorbis playback,
    audio/video streaming to complex audio (mixing) and video
    (non-linear editing) processing.
  doc_url: https://gstreamer.freedesktop.org/documentation/
  dev_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - msarahan
    - tschoonj
    - scopatz
