{% set version = "1.14.1" %}
{% set sha256 = "28d82b0d261544a9bf85b429399929e4986eb00efcf1ce16cc71d269a4c3186c" %}
{% set plugin_base_sha256 = "1026c7c3082d825d9b5d034c1a6dd8a4ebab60eb3738b0a0afde4ad2dc0b0db5" %}

package:
  name: gstreamer_and_plugins
  version: {{ version }}

source:
  - url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
    sha256: {{ sha256 }}
    # patches:
    #   - patches/CVE-2022-1920_gstreamer_commit_cf887f1.patch
    #   - patches/CVE-2022-1921_gstreamer_commit_f503caa.patch
    #   - patches/CVE-2022-1922_CVE-2022-1923_CVE-2022-1924_CVE-2022-1925_gstreamer_commit_ad60121.patch
    #   - patches/CVE-2022-2122_gstreamer_commit_14d306d.patch
  - url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-{{ version }}.tar.xz
    sha256: {{ plugin_base_sha256 }}
    folder: plugins_base
    patches:
      - patches/CVE-2019-9928_gstreamer_pull_157.patch

build:
  skip: true  # [win or osx or (linux and s390x)]
  number: 2

outputs:
  - name: gstreamer
    script: install_gstreamer.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gstreamer', max_pin='x.x') }}

    requirements:
{% if target_platform == 'linux-64' %}
      build:
        - patch
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 1_gnu
        - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
        - binutils_impl_linux-64 2.38 h2a08ee3_1
        - binutils_linux-64 2.38.0 hc2dff05_0
        - bison 3.7.5 h2531618_1
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2023.01.10 h06a4308_0
        - flex 2.6.4 ha10e3a4_1
        - gcc_impl_linux-64 11.2.0 h1234567_1
        - gcc_linux-64 11.2.0 h5c386dc_0
        - glib 2.69.1 he621ea3_2
        - gobject-introspection 1.72.0 py310hbb6d50b_1
        - kernel-headers_linux-64 3.10.0 h57e8cba_10
        - ld_impl_linux-64 2.38 h1181459_1
        - libffi 3.4.2 h6a678d5_6
        - libgcc-devel_linux-64 11.2.0 h1234567_1
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - libuuid 1.41.5 h5eee18b_0
        - m4 1.4.18 h4e445db_0
        - meson 0.64.1 py310h06a4308_0
        - ncurses 6.4 h6a678d5_0
        - ninja 1.10.2 h06a4308_5
        - ninja-base 1.10.2 hd09550d_5
        - openssl 1.1.1t h7f8727e_0
        - pcre 8.45 h295c915_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.10.9 h7a1cb2a_0
        - readline 8.2 h5eee18b_0
        - sqlite 3.40.1 h5082296_0
        - sysroot_linux-64 2.17 h57e8cba_10
        - tk 8.6.12 h1ccaba5_0
        - tzdata 2022g h04d1e81_0
        - xz 5.2.10 h5eee18b_1
        - zlib 1.2.13 h5eee18b_0
      host:
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 1_gnu
        - glib 2.69.1 he621ea3_2
        - libffi 3.4.2 h6a678d5_6
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - pcre 8.45 h295c915_0
        - zlib 1.2.13 h5eee18b_0
      run:
        - glib >=2.69.1,<3.0a0
        - libgcc-ng >=11.2.0
{% elif target_platform == 'linux-aarch64' %}
      build:
        - patch
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 51_gnu
        - binutils_impl_linux-aarch64 2.38 h0c9fd12_1
        - binutils_linux-aarch64 2.38.0 h0c7b1b4_0
        - bison 3.7.5 h22f4aa5_1
        - bzip2 1.0.8 hfd63f10_2
        - ca-certificates 2023.01.10 hd43f75c_0
        - flex 2.6.4 h7c1a80f_1
        - gcc_impl_linux-aarch64 11.2.0 h1234567_1
        - gcc_linux-aarch64 11.2.0 h3fc98b3_0
        - glib 2.69.1 h94b7715_2
        - gobject-introspection 1.72.0 py310ha19700e_1
        - kernel-headers_linux-aarch64 4.14.214 h1cb168f_14
        - ld_impl_linux-aarch64 2.38 h8131f2d_1
        - libffi 3.4.2 h419075a_6
        - libgcc-devel_linux-aarch64 11.2.0 h1234567_1
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - libuuid 1.41.5 h998d150_0
        - m4 1.4.18 hfd63f10_1
        - meson 0.64.1 py310hd43f75c_0
        - ncurses 6.4 h419075a_0
        - ninja 1.10.2 hd43f75c_5
        - ninja-base 1.10.2 h59a28a9_5
        - openssl 1.1.1t h2f4d8fa_0
        - pcre 8.45 h22f4aa5_0
        - pkg-config 0.29.2 h2f4d8fa_0
        - python 3.10.9 h89984f6_0
        - readline 8.2 h998d150_0
        - sqlite 3.40.1 hf533066_0
        - sysroot_linux-aarch64 2.26 h4744778_14
        - tk 8.6.12 h241ca14_0
        - tzdata 2022g h04d1e81_0
        - xz 5.2.10 h998d150_1
        - zlib 1.2.13 h998d150_0
      host:
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 51_gnu
        - glib 2.69.1 h94b7715_2
        - libffi 3.4.2 h419075a_6
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - pcre 8.45 h22f4aa5_0
        - zlib 1.2.13 h998d150_0
      run:
        - glib >=2.69.1,<3.0a0
        - libgcc-ng >=11.2.0
{% else %}
      build:
        - {{ compiler('c') }}
        - pkg-config
        - bison
        - flex
        - m4
        - autoconf
        - automake
        - make
        - perl
        - libtool
        - patch
      host:
        - gobject-introspection
        - gettext                            # [osx]
        - pcre                               # [linux]
        - libffi                             # [linux]
        - glib
        - xz
{% endif %}
    test:
      commands:
        - gst-inspect-1.0 --version
        - gst-launch-1.0  --version
        - gst-stats-1.0 --version
        - gst-typefind-1.0 --version
    about:
      summary: "Library for constructing graphs of media-handling components"
      description:
      doc_source_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/docs

  - name: gst-plugins-base
    script: install_base_plugins.sh
    build:
      activate_in_script: True
      run_exports:
        # remove symbols at .90 patch releases just before minor versions?
        #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
        - {{ pin_subpackage('gst-plugins-base', max_pin='x.x') }}

    requirements:
{% if target_platform == 'linux-64' %}
      build:
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 1_gnu
        - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
        - binutils_impl_linux-64 2.38 h2a08ee3_1
        - binutils_linux-64 2.38.0 hc2dff05_0
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2023.01.10 h06a4308_0
        - expat-cos6-x86_64 2.0.1 4
        - gcc_impl_linux-64 11.2.0 h1234567_1
        - gcc_linux-64 11.2.0 h5c386dc_0
        - glib 2.69.1 he621ea3_2
        - gobject-introspection 1.72.0 py310hbb6d50b_1
        - gxx_impl_linux-64 11.2.0 h1234567_1
        - gxx_linux-64 11.2.0 hc2dff05_0
        - kernel-headers-cos6-x86_64 2.6.32 4
        - kernel-headers_linux-64 3.10.0 h57e8cba_10
        - ld_impl_linux-64 2.38 h1181459_1
        - libdrm-cos6-x86_64 2.4.65 4
        - libdrm-devel-cos6-x86_64 2.4.65 4
        - libffi 3.4.2 h6a678d5_6
        - libgcc-devel_linux-64 11.2.0 h1234567_1
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libselinux-cos6-x86_64 2.0.94 4
        - libselinux-devel-cos6-x86_64 2.0.94 4
        - libsepol-cos6-x86_64 2.0.41 4
        - libsepol-devel-cos6-x86_64 2.0.41 4
        - libstdcxx-devel_linux-64 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - libuuid 1.41.5 h5eee18b_0
        - libx11-common-cos6-x86_64 1.6.4 4
        - libx11-cos6-x86_64 1.6.4 4
        - libx11-devel-cos6-x86_64 1.6.4 4
        - libxau-cos6-x86_64 1.0.6 4
        - libxau-devel-cos6-x86_64 1.0.6 4
        - libxdamage-cos6-x86_64 1.1.3 4
        - libxdamage-devel-cos6-x86_64 1.1.3 4
        - libxext-cos6-x86_64 1.3.3 4
        - libxext-devel-cos6-x86_64 1.3.3 4
        - libxfixes-cos6-x86_64 5.0.3 4
        - libxfixes-devel-cos6-x86_64 5.0.3 4
        - libxrender-cos6-x86_64 0.9.10 4
        - libxrender-devel-cos6-x86_64 0.9.10 4
        - libxxf86vm-cos6-x86_64 1.1.3 4
        - libxxf86vm-devel-cos6-x86_64 1.1.3 4
        - mesa-dri-drivers-cos6-x86_64 11.0.7 4
        - mesa-dri1-drivers-cos6-x86_64 7.11 4
        - mesa-libegl-cos6-x86_64 11.0.7 4
        - mesa-libegl-devel-cos6-x86_64 11.0.7 4
        - mesa-libgbm-cos6-x86_64 11.0.7 4
        - mesa-libgl-cos6-x86_64 11.0.7 4
        - mesa-libgl-devel-cos6-x86_64 11.0.7 4
        - meson 0.64.1 py310h06a4308_0
        - ncurses 6.4 h6a678d5_0
        - ninja 1.10.2 h06a4308_5
        - ninja-base 1.10.2 hd09550d_5
        - openssl 1.1.1t h7f8727e_0
        - pcre 8.45 h295c915_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.10.9 h7a1cb2a_0
        - readline 8.2 h5eee18b_0
        - sqlite 3.40.1 h5082296_0
        - sysroot_linux-64 2.17 h57e8cba_10
        - tk 8.6.12 h1ccaba5_0
        - tzdata 2022g h04d1e81_0
        - xorg-x11-proto-devel-cos6-x86_64 7.7 4
        - xz 5.2.10 h5eee18b_1
        - zlib 1.2.13 h5eee18b_0
      host:
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 1_gnu
        - glib 2.69.1 h4ff587b_1
        - gstreamer >=1.14.1,<2.0a0
        - libffi 3.3 he6710b0_2
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - libxcb 1.14 h7b6447c_0
        - pcre 8.45 h295c915_0
        - pthread-stubs 0.3 h0ce48e5_1
        - zlib 1.2.11 h7f8727e_4
      run:
        - glib >=2.69.1,<3.0a0
        - gstreamer >=1.14.1,<2.0a0
        - libgcc-ng >=11.2.0
        - libstdcxx-ng >=11.2.0
        - libxcb >=1.14,<2.0a0
        - zlib >=1.2.11,<1.3.0a0
{% elif target_platform == 'linux-arch64' %}
      build:
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 51_gnu
        - acl-amzn2-aarch64 2.2.51 5
        - audit-libs-amzn2-aarch64 2.8.1 5
        - basesystem-amzn2-aarch64 10.0 5
        - binutils_impl_linux-aarch64 2.38 h0c9fd12_1
        - binutils_linux-aarch64 2.38.0 h0c7b1b4_0
        - bzip2 1.0.8 hfd63f10_2
        - bzip2-libs-amzn2-aarch64 1.0.6 5
        - ca-certificates 2023.01.10 hd43f75c_0
        - coreutils-amzn2-aarch64 8.22 5
        - cracklib-amzn2-aarch64 2.9.0 5
        - cracklib-dicts-amzn2-aarch64 2.9.0 5
        - cryptsetup-libs-amzn2-aarch64 1.7.4 5
        - dbus-amzn2-aarch64 1.10.24 5
        - dbus-libs-amzn2-aarch64 1.10.24 5
        - device-mapper-libs-amzn2-aarch64 1.02.146 5
        - diffutils-amzn2-aarch64 3.3 5
        - elfutils-default-yama-scope-amzn2-aarch64 0.176 5
        - elfutils-libelf-amzn2-aarch64 0.176 5
        - elfutils-libs-amzn2-aarch64 0.176 5
        - expat-amzn2-aarch64 2.1.0 5
        - filesystem-amzn2-aarch64 3.2 5
        - gawk-amzn2-aarch64 4.0.2 5
        - gcc_impl_linux-aarch64 11.2.0 h1234567_1
        - gcc_linux-aarch64 11.2.0 h3fc98b3_0
        - gl-manpages-amzn2-aarch64 1.1 5
        - glib 2.69.1 h94b7715_2
        - glib2-amzn2-aarch64 2.56.1 5
        - glibc-amzn2-aarch64 2.26 5
        - glibc-common-amzn2-aarch64 2.26 5
        - glibc-minimal-langpack-amzn2-aarch64 2.26 5
        - gmp-amzn2-aarch64 6.0.0 5
        - gobject-introspection 1.72.0 py310ha19700e_1
        - grep-amzn2-aarch64 2.20 5
        - gxx_impl_linux-aarch64 11.2.0 h1234567_1
        - gxx_linux-aarch64 11.2.0 h0c7b1b4_0
        - gzip-amzn2-aarch64 1.5 5
        - info-amzn2-aarch64 5.1 5
        - kernel-headers-amzn2-aarch64 4.14.214 5
        - kernel-headers_linux-aarch64 4.14.214 h1cb168f_14
        - kmod-amzn2-aarch64 25 5
        - kmod-libs-amzn2-aarch64 25 5
        - ld_impl_linux-aarch64 2.38 h8131f2d_1
        - libacl-amzn2-aarch64 2.2.51 5
        - libattr-amzn2-aarch64 2.4.46 5
        - libblkid-amzn2-aarch64 2.30.2 5
        - libcap-amzn2-aarch64 2.22 5
        - libcap-ng-amzn2-aarch64 0.7.5 5
        - libcrypt-amzn2-aarch64 2.26 5
        - libcurl-amzn2-aarch64 7.61.1 5
        - libdb-amzn2-aarch64 5.3.21 5
        - libdrm-amzn2-aarch64 2.4.97 5
        - libdrm-devel-amzn2-aarch64 2.4.97 5
        - libffi 3.4.2 h419075a_6
        - libffi-amzn2-aarch64 3.0.13 5
        - libgcc-amzn2-aarch64 7.3.1 5
        - libgcc-devel_linux-aarch64 11.2.0 h1234567_1
        - libgcc-ng 11.2.0 h1234567_1
        - libgcrypt-amzn2-aarch64 1.5.3 5
        - libglvnd-amzn2-aarch64 1.0.1 5
        - libglvnd-core-devel-amzn2-aarch64 1.0.1 5
        - libglvnd-devel-amzn2-aarch64 1.0.1 5
        - libglvnd-egl-amzn2-aarch64 1.0.1 5
        - libglvnd-gles-amzn2-aarch64 1.0.1 5
        - libglvnd-glx-amzn2-aarch64 1.0.1 5
        - libglvnd-opengl-amzn2-aarch64 1.0.1 5
        - libgomp 11.2.0 h1234567_1
        - libgpg-error-amzn2-aarch64 1.12 5
        - libmount-amzn2-aarch64 2.30.2 5
        - libpwquality-amzn2-aarch64 1.2.3 5
        - libselinux-amzn2-aarch64 2.5 5
        - libselinux-devel-amzn2-aarch64 2.5 5
        - libsepol-amzn2-aarch64 2.5 5
        - libsepol-devel-amzn2-aarch64 2.5 5
        - libstdcxx-amzn2-aarch64 7.3.1 5
        - libstdcxx-devel_linux-aarch64 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - libuuid 1.41.5 h998d150_0
        - libuuid-amzn2-aarch64 2.30.2 5
        - libwayland-client-amzn2-aarch64 1.17.0 5
        - libwayland-server-amzn2-aarch64 1.17.0 5
        - libx11-amzn2-aarch64 1.6.7 5
        - libx11-common-amzn2-aarch64 1.6.7 5
        - libx11-devel-amzn2-aarch64 1.6.7 5
        - libxau-amzn2-aarch64 1.0.8 5
        - libxau-devel-amzn2-aarch64 1.0.8 5
        - libxcb-amzn2-aarch64 1.12 5
        - libxdamage-amzn2-aarch64 1.1.4 5
        - libxdamage-devel-amzn2-aarch64 1.1.4 5
        - libxext-amzn2-aarch64 1.3.3 5
        - libxext-devel-amzn2-aarch64 1.3.3 5
        - libxfixes-amzn2-aarch64 5.0.3 5
        - libxfixes-devel-amzn2-aarch64 5.0.3 5
        - libxml2-amzn2-aarch64 2.9.1 5
        - libxrender-amzn2-aarch64 0.9.10 5
        - libxrender-devel-amzn2-aarch64 0.9.10 5
        - libxshmfence-amzn2-aarch64 1.2 5
        - libxxf86vm-amzn2-aarch64 1.1.4 5
        - libxxf86vm-devel-amzn2-aarch64 1.1.4 5
        - llvm-private-amzn2-aarch64 6.0.1 5
        - lz4-amzn2-aarch64 1.7.5 5
        - mesa-dri-drivers-amzn2-aarch64 18.3.4 5
        - mesa-filesystem-amzn2-aarch64 18.3.4 5
        - mesa-khr-devel-amzn2-aarch64 18.3.4 5
        - mesa-libegl-amzn2-aarch64 18.3.4 5
        - mesa-libegl-devel-amzn2-aarch64 18.3.4 5
        - mesa-libgbm-amzn2-aarch64 18.3.4 5
        - mesa-libgl-amzn2-aarch64 18.3.4 5
        - mesa-libgl-devel-amzn2-aarch64 18.3.4 5
        - mesa-libglapi-amzn2-aarch64 18.3.4 5
        - meson 0.64.1 py310hd43f75c_0
        - ncurses 6.4 h419075a_0
        - ncurses-amzn2-aarch64 6.0 5
        - ncurses-base-amzn2-aarch64 6.0 5
        - ncurses-libs-amzn2-aarch64 6.0 5
        - ninja 1.10.2 hd43f75c_5
        - ninja-base 1.10.2 h59a28a9_5
        - openssl 1.1.1t h2f4d8fa_0
        - pam-amzn2-aarch64 1.1.8 5
        - pcre 8.45 h22f4aa5_0
        - pcre-amzn2-aarch64 8.32 5
        - pkg-config 0.29.2 h2f4d8fa_0
        - pkgconfig-amzn2-aarch64 0.27.1 5
        - python 3.10.9 h89984f6_0
        - qrencode-libs-amzn2-aarch64 3.4.1 5
        - readline 8.2 h998d150_0
        - sed-amzn2-aarch64 4.2.2 5
        - setup-amzn2-aarch64 2.8.71 5
        - shared-mime-info-amzn2-aarch64 1.8 5
        - sqlite 3.40.1 hf533066_0
        - sysroot_linux-aarch64 2.26 h4744778_14
        - system-release-amzn2-aarch64 2 5
        - systemd-amzn2-aarch64 219 5
        - systemd-libs-amzn2-aarch64 219 5
        - tk 8.6.12 h241ca14_0
        - tzdata 2022g h04d1e81_0
        - tzdata-amzn2-aarch64 2020d 5
        - xorg-x11-proto-devel-amzn2-aarch64 2018.4 5
        - xz 5.2.10 h998d150_1
        - xz-libs-amzn2-aarch64 5.2.2 5
        - zlib 1.2.13 h998d150_0
        - zlib-amzn2-aarch64 1.2.7 5
      host:
        - _libgcc_mutex 0.1 main
        - _openmp_mutex 5.1 51_gnu
        - glib 2.69.1 h549d06d_1
        - gstreamer >=1.14.1,<2.0a0
        - libffi 3.3 h7c1a80f_2
        - libgcc-ng 11.2.0 h1234567_1
        - libgomp 11.2.0 h1234567_1
        - libstdcxx-ng 11.2.0 h1234567_1
        - libxcb 1.14 hfd63f10_0
        - pcre 8.45 h22f4aa5_0
        - pthread-stubs 0.3 hfd63f10_1
        - zlib 1.2.11 hfd63f10_5
      run:
        - glib >=2.69.1,<3.0a0
        - gstreamer >=1.14.1,<2.0a0
        - libgcc-ng >=11.2.0
        - libstdcxx-ng >=11.2.0
        - libxcb >=1.14,<2.0a0
        - zlib >=1.2.11,<1.3.0a0
{% else %}
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ cdt('libxau-devel') }}          # [linux]
        - {{ cdt('libxext-devel') }}         # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxrender-devel') }}      # [linux]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('mesa-libgl-devel') }}      # [linux]
        - {{ cdt('libdrm-devel') }}          # [linux]
        - {{ cdt('libxdamage-devel') }}      # [linux]
        - {{ cdt('libxfixes-devel') }}       # [linux]
        - {{ cdt('libxxf86vm-devel') }}      # [linux]
        - pkg-config
        - m4
        - autoconf
        - automake
        - make
        - perl
        - libtool # [not win]
      host:
        - {{ pin_subpackage('gstreamer') }}
        - glib
        - zlib
        - gettext                            # [osx]
        - libxcb                             # [linux]
        - pthread-stubs                      # [linux]
        - xz
      run:
        - {{ pin_compatible('gstreamer') }}
{% endif %}

    test:
      commands:
        {% set SOEXT = 'dylib' if osx else 'so' %}
        - test -f $PREFIX/lib/libgstallocators-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstapp-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstaudio-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstfft-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstpbutils-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstriff-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstrtp-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstrtsp-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstsdp-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgsttag-1.0.{{ SOEXT }}
        - test -f $PREFIX/lib/libgstvideo-1.0.{{ SOEXT }}

    about:
        summary: "GStreamer Base Plug-ins"
        description: |
          GStreamer Base Plug-ins is a well-groomed and well-maintained collection of
          GStreamer plug-ins and elements, spanning the range of possible types of
          elements one would want to write for GStreamer.
        doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs



about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL 2
  doc_url: https://gstreamer.freedesktop.org/documentation/
  dev_url: https://cgit.freedesktop.org/gstreamer/gstreamer/tree/

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - msarahan
