travis:
  secure:
    BINSTAR_TOKEN: geUjczFz4CidkfizrKtW5S2kdTqcUzUIYUL1xPML8wWIdn35d0Vh10VQ9MyLrjEV/B5+QBdzNJwvIwOfLw7fZbxwLstiD04n5C1N07wqfOMRcUtHqZCgnrQnb19uOYUxzqcTiG7lQVLMDKCRbLbxZA3JFJz8KB6C4HkFKXnp7UHHa5pqXoWRwoF9FMraYxa9tXs6hYC3/erMNzpXNAIjwYGNB13e/lObwznd9eBLHzJwOp+8rYV1C34FW032qBI/fv4eP8+bdlI8EuUpEVYHbXuK1u0/m/4R7gC+yDhbn8Da0/EpiFLihiuhhW+KXL8XD7MMOf8RXlhXuhvtd5xoVelBtDXFWONWLuQzhUVqKQSRpbfpSdbuxLVb0FexyBtkPfhSa19MwsxGglNwro6nIPK7jQI+cY15Rrjd3OaDTwWwNH0JCELjQ9vO982UVDcSR4Mo5HOGn/ng3NNGXO2hTSUXaYtmidp9x8mD4Hu+9tc5HV9bT+TuM4TgcU6jFxMi8a1pk671k2E2CUbFjt2go0Lgl7a1Eafl5LiuGz7Is9l4A2X1dGoo1ONQuZnWabENalbazrYRAxQAwA2K7tFDhtK+beEeke0wfCvIgs+CmVAnC4ZSucImIu817irA9ghSZyagNBR5EAFaCCAu5BPrzCxqdTkHuZXOnWoMu5veYuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
