travis:
  secure:
    BINSTAR_TOKEN: YYjSDmVJ+1Ccv/9gpvLlOLfq1dgV3wHNYEz4C4nN3QaitkXfUttmMoeFrub03ye6t+1crdtzIEgx7J4KJXvbbcCQVQ/TdpfRouxN+tYMdDAh90XhAbPbsEKSbe6Xm00VLeSHYkKXSQaon0HXCy0hGBMFThL9zxPJksjCg+NTVd3ojlvAq2NIqScOMuQquM9O16TmO3gLg81yFLUGTtrHDv8eEPXpvjtSFW6WwGmRv+sm0MmwdZIN5YLudOIyw2rRGoBSNh3vW3MO1dprD/9Y0QfXVCQt56dN5ufpwcvFOvdCFSoACgzZ5JVdeOACQ0anFQ5nQ9hdKL3rouRte8x3v3XocwOTZChixZtUdxVqFuuyN7NqJswwIr0Uxm/hZqPRJegMQIbMjvZx36IcHKkhKcun8TjQIeRlVDFEhllJSFamOrFHtf6cmEM8KMrF+ZZlvW6Bm+rropJF35XeQXIcyXn0SvAySOtLyBCblu6Sg0Fr+GLyTQ7W3M58h/3u7Ys8hf4cCJJA5x/A/pGKe75j8Tps/JqsAgxn87lJn5Sl6FT3PGk8IEpfI1TsLoH4WyOLVf7bSDXQcSPm0kuaB1rKvr5R6AoX9CTeZnAtDwISwNUL2CKVJL3BpV/J2TyTEHkwJYITq7SS0wZl6WR2m2nREjnJRhulD0g3odHbbkOjOio=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
